apiVersion: v1
kind: Service
metadata:
  name: agent-sdk
  labels:
    app: agent-sdk
spec:
  selector:
    app: agent-sdk
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
